version: '3'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine. 
# The ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like: 
#     ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${ESHOP_REDIS_CONNECTION}
      - identityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105         #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105. 
      - AzureServiceBusEnabled=true
      - EventBusConnection=${ESHOP_EVENT_BUS_CONNECTION}
    ports:
      - "5103:80"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${ESHOP_AZUREDB_CONNECTION};Database=${ESHOP_AZURE_DB_PREFIX}CatalogDb
      - ExternalCatalogBaseUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5101    #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105.	  
      - AzureServiceBusEnabled=true
      - EventBusConnection=${ESHOP_EVENT_BUS_CONNECTION}
    ports:
      - "5101:80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SpaClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5104
      - ConnectionStrings__DefaultConnection=${ESHOP_AZUREDB_CONNECTION};Database=${ESHOP_AZURE_DB_PREFIX}IdentityDb
      - MvcClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5100              #Local: You need to open your local dev-machine firewall at range 5100-5105.  
    ports:
      - "5105:80"

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${ESHOP_AZUREDB_CONNECTION};Database=${ESHOP_AZURE_DB_PREFIX}OrderingDb
      - identityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105            #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105. 
      - AzureServiceBusEnabled=true
      - EventBusConnection=${ESHOP_EVENT_BUS_CONNECTION}
    ports:
      - "5102:80"

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CatalogUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5101
      - OrderingUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5102
      - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105              #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105. 
      - BasketUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5103                
      - CatalogUrlHC=http://catalog.api/hc
      - OrderingUrlHC=http://ordering.api/hc
      - IdentityUrlHC=http://identity.api/hc     #Local: Use ${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}, if using external IP or DNS name from browser.          
      - BasketUrlHC=http://basket.api/hc      
    ports:
      - "5104:80"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CatalogUrl=http://catalog.api
      - OrderingUrl=http://ordering.api
      - BasketUrl=http://basket.api
      - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105      #Local:  Use 10.0.75.1 in a "Docker for Windows" environment, if using "localhost" from browser. 
                                                                        #Remote: Use ${ESHOP_EXTERNAL_DNS_NAME_OR_IP} if using external IP or DNS name from browser. 
    ports:
      - "5100:80"

  locations.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${AZURE_COSMOSDB}
      - Database=LocationsDb
      - identityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105      #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105. 
      - AzureServiceBusEnabled=true
      - EventBusConnection=${ESHOP_EVENT_BUS_CONNECTION}
    ports:
      - "5109:80"

  marketing.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${ESHOP_AZUREDB_CONNECTION};Database=${ESHOP_AZURE_DB_PREFIX}MarketingDb
      - AzureServiceBusEnabled=true
      - EventBusConnection=${ESHOP_EVENT_BUS_CONNECTION}
      - MongoConnectionString=${AZURE_COSMOSDB}
      - MongoDatabase=MarketingDb
      - identityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105       #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105. 
    ports:
      - "5110:80"